#ifndef __COMMON__
#define __COMMON__

#define DEBUG_DEVICE 0

#define DEBUG_INPUT_DATA 0
#define DEBUG_INIT_CENTROIDS 0

#define DEBUG_KERNELS_INVOKATION 1

#define DEBUG_KERNEL_DISTANCES 0
#define DEBUG_KERNEL_ARGMIN 0
#define DEBUG_KERNEL_CENTROIDS 0

#define PERFORMANCES_KERNEL_DISTANCES 1
#define PERFORMANCES_KERNEL_ARGMIN 0
#define PERFORMANCES_KERNEL_CENTROIDS 1

#define DEBUG_OUTPUT_INFO 1

#define DATA_TYPE float

#endif