#ifndef __COMMON__
#define __COMMON__

#define DEBUG_DEVICE 0
#define DEBUG_INPUT_DATA 1
#define DEBUG_INIT_CENTERS 1
#define DEBUG_KERNELS_INVOKATION 1
#define DEBUG_KERNEL_DISTANCES 1
#define DEBUG_KERNEL_ARGMIN 1
#define DEBUG_KERNEL_CENTERS 1

#define DATA_TYPE float

#endif